import type { Metadata } from "next";
import { montserrat, openSans, poppins } from "@/public/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Base Packer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${openSans.variable} ${poppins.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
